# F2018065101
# Raja Faizan Nazir

car_mpg_car_name = [[18, 'chevrolet chevelle malibu'],
                    [15, 'buick skylark 320'],
                    [18, 'plymouth satellite'],
                    [16, 'amc rebel sst'],
                    [17, 'ford torino'],
                    [15, 'ford galaxie 500'],
                    [14, 'chevrolet impala'],
                    [14, 'plymouth fury iii'],
                    [14, 'pontiac catalina'],
                    [15, 'amc ambassador dpl'],
                    [15, 'dodge challenger se'],
                    [14, 'plymouth cuda 340'],
                    [15, 'chevrolet monte carlo'],
                    [14, 'buick estate wagon (sw)'],
                    [24, 'toyota corona mark ii'],
                    [22, 'plymouth duster'],
                    [18, 'amc hornet'],
                    [21, 'ford maverick'],
                    [27, 'datsun pl510'],
                    [26, 'volkswagen 1131 deluxe sedan'],
                    [25, 'peugeot 504'],
                    [24, 'audi 100 ls'],
                    [25, 'saab 99e'],
                    [26, 'bmw 2002'],
                    [21, 'amc gremlin'],
                    [10, 'ford f250'],
                    [10, 'chevy c20'],
                    [11, 'dodge d200'],
                    [28, 'chevrolet vega 2300'],
                    [25, 'toyota corona'],
                    [19, 'amc gremlin'],
                    [16, 'plymouth satellite custom'],
                    [17, 'chevrolet chevelle malibu'],
                    [19, 'ford torino 500'],
                    [18, 'amc matador'],
                    [14, 'chevrolet impala'],
                    [14, 'pontiac catalina brougham'],
                    [14, 'ford galaxie 500'],
                    [14, 'plymouth fury iii'],
                    [12, 'dodge monaco (sw)'],
                    [13, 'ford country squire (sw)'],
                    [13, 'pontiac safari (sw)'],
                    [18, 'amc hornet sportabout (sw)'],
                    [22, 'chevrolet vega (sw)'],
                    [19, 'pontiac firebird'],
                    [18, 'ford mustang'],
                    [23, 'mercury capri 2000'],
                    [28, 'opel 1900'],
                    [30, 'peugeot 304'],
                    [30, 'fiat 124b'],
                    [31, 'toyota corolla 1200'],
                    [35, 'datsun 1200'],
                    [27, 'volkswagen model 111'],
                    [26, 'plymouth cricket'],
                    [24, 'toyota corona hardtop'],
                    [25, 'dodge colt hardtop'],
                    [23, 'volkswagen type 3'],
                    [20, 'chevrolet vega'],
                    [21, 'ford pinto runabout'],
                    [13, 'chevrolet impala'],
                    [14, 'pontiac catalina'],
                    [15, 'plymouth fury iii'],
                    [14, 'ford galaxie 500'],
                    [17, 'amc ambassador sst'],
                    [11, 'mercury marquis'],
                    [13, 'buick lesabre custom'],
                    [12, 'oldsmobile delta 88 royale'],
                    [13, 'chrysler newport royal'],
                    [19, 'mazda rx2 coupe'],
                    [15, 'amc matador (sw)'],
                    [13, 'chevrolet chevelle concours (sw)'],
                    [13, 'ford gran torino (sw)'],
                    [14, 'plymouth satellite custom (sw)'],
                    [18, 'volvo 145e (sw)'],
                    [22, 'volkswagen 411 (sw)'],
                    [21, 'peugeot 504 (sw)'],
                    [26, 'renault 12 (sw)'],
                    [22, 'ford pinto (sw)'],
                    [28, 'datsun 510 (sw)'],
                    [23, 'toyouta corona mark ii (sw)'],
                    [28, 'dodge colt (sw)'],
                    [27, 'toyota corolla 1600 (sw)'],
                    [13, 'buick century 350'],
                    [14, 'amc matador'],
                    [13, 'chevrolet malibu'],
                    [14, 'ford gran torino'],
                    [15, 'dodge coronet custom'],
                    [12, 'mercury marquis brougham'],
                    [13, 'chevrolet caprice classic'],
                    [13, 'ford ltd'],
                    [14, 'plymouth fury gran sedan'],
                    [13, 'chrysler new yorker brougham'],
                    [12, 'buick electra 225 custom'],
                    [13, 'amc ambassador brougham'],
                    [18, 'plymouth valiant'],
                    [16, 'chevrolet nova custom'],
                    [18, 'amc hornet'],
                    [18, 'ford maverick'],
                    [23, 'plymouth duster'],
                    [26, 'volkswagen super beetle'],
                    [11, 'chevrolet impala'],
                    [12, 'ford country'],
                    [13, 'plymouth custom suburb'],
                    [12, 'oldsmobile vista cruiser'],
                    [18, 'amc gremlin'],
                    [20, 'toyota carina'],
                    [21, 'chevrolet vega'],
                    [22, 'datsun 610'],
                    [18, 'maxda rx3'],
                    [19, 'ford pinto'],
                    [21, 'mercury capri v6'],
                    [26, 'fiat 124 sport coupe'],
                    [15, 'chevrolet monte carlo s'],
                    [16, 'pontiac grand prix'],
                    [29, 'fiat 128'],
                    [24, 'opel manta'],
                    [20, 'audi 100ls'],
                    [19, 'volvo 144ea'],
                    [15, 'dodge dart custom'],
                    [24, 'saab 99le'],
                    [20, 'toyota mark ii'],
                    [11, 'oldsmobile omega'],
                    [20, 'plymouth duster'],
                    [19, 'amc hornet'],
                    [15, 'chevrolet nova'],
                    [31, 'datsun b210'],
                    [26, 'ford pinto'],
                    [32, 'toyota corolla 1200'],
                    [25, 'chevrolet vega'],
                    [16, 'chevrolet chevelle malibu classic'],
                    [16, 'amc matador'],
                    [18, 'plymouth satellite sebring'],
                    [16, 'ford gran torino'],
                    [13, 'buick century luxus (sw)'],
                    [14, 'dodge coronet custom (sw)'],
                    [14, 'ford gran torino (sw)'],
                    [14, 'amc matador (sw)'],
                    [29, 'audi fox'],
                    [26, 'volkswagen dasher'],
                    [26, 'opel manta'],
                    [31, 'toyota corona'],
                    [32, 'datsun 710'],
                    [28, 'dodge colt'],
                    [24, 'fiat 128'],
                    [26, 'fiat 124 tc'],
                    [24, 'honda civic'],
                    [26, 'subaru'],
                    [31, 'fiat x1.9'],
                    [19, 'plymouth valiant custom'],
                    [18, 'chevrolet nova'],
                    [15, 'mercury monarch'],
                    [15, 'ford maverick'],
                    [16, 'pontiac catalina'],
                    [15, 'chevrolet bel air'],
                    [16, 'plymouth grand fury'],
                    [14, 'ford ltd'],
                    [17, 'buick century'],
                    [16, 'chevroelt chevelle malibu'],
                    [15, 'amc matador'],
                    [18, 'plymouth fury'],
                    [21, 'buick skyhawk'],
                    [20, 'chevrolet monza 2+2'],
                    [13, 'ford mustang ii'],
                    [29, 'toyota corolla'],
                    [23, 'ford pinto'],
                    [20, 'amc gremlin'],
                    [23, 'pontiac astro'],
                    [24, 'toyota corona'],
                    [25, 'volkswagen dasher'],
                    [24, 'datsun 710'],
                    [18, 'ford pinto'],
                    [29, 'volkswagen rabbit'],
                    [19, 'amc pacer'],
                    [23, 'audi 100ls'],
                    [23, 'peugeot 504'],
                    [22, 'volvo 244dl'],
                    [25, 'saab 99le'],
                    [33, 'honda civic cvcc'],
                    [28, 'fiat 131'],
                    [25, 'opel 1900'],
                    [25, 'capri ii'],
                    [26, 'dodge colt'],
                    [27, 'renault 12tl'],
                    [17.5, 'chevrolet chevelle malibu classic'],
                    [16, 'dodge coronet brougham'],
                    [15.5, 'amc matador'],
                    [14.5, 'ford gran torino'],
                    [22, 'plymouth valiant'],
                    [22, 'chevrolet nova'],
                    [24, 'ford maverick'],
                    [22.5, 'amc hornet'],
                    [29, 'chevrolet chevette'],
                    [24.5, 'chevrolet woody'],
                    [29, 'vw rabbit'],
                    [33, 'honda civic'],
                    [20, 'dodge aspen se'],
                    [18, 'ford granada ghia'],
                    [18.5, 'pontiac ventura sj'],
                    [17.5, 'amc pacer d/l'],
                    [29.5, 'volkswagen rabbit'],
                    [32, 'datsun b-210'],
                    [28, 'toyota corolla'],
                    [26.5, 'ford pinto'],
                    [20, 'volvo 245'],
                    [13, 'plymouth volare premier v8'],
                    [19, 'peugeot 504'],
                    [19, 'toyota mark ii'],
                    [16.5, 'mercedes-benz 280s'],
                    [16.5, 'cadillac seville'],
                    [13, 'chevy c10'],
                    [13, 'ford f108'],
                    [13, 'dodge d100'],
                    [31.5, 'honda accord cvcc'],
                    [30, 'buick opel isuzu deluxe'],
                    [36, 'renault 5 gtl'],
                    [25.5, 'plymouth arrow gs'],
                    [33.5, 'datsun f-10 hatchback'],
                    [17.5, 'chevrolet caprice classic'],
                    [17, 'oldsmobile cutlass supreme'],
                    [15.5, 'dodge monaco brougham'],
                    [15, 'mercury cougar brougham'],
                    [17.5, 'chevrolet concours'],
                    [20.5, 'buick skylark'],
                    [19, 'plymouth volare custom'],
                    [18.5, 'ford granada'],
                    [16, 'pontiac grand prix lj'],
                    [15.5, 'chevrolet monte carlo landau'],
                    [15.5, 'chrysler cordoba'],
                    [16, 'ford thunderbird'],
                    [29, 'volkswagen rabbit custom'],
                    [24.5, 'pontiac sunbird coupe'],
                    [26, 'toyota corolla liftback'],
                    [25.5, 'ford mustang ii 2+2'],
                    [30.5, 'chevrolet chevette'],
                    [33.5, 'dodge colt m/m'],
                    [30, 'subaru dl'],
                    [30.5, 'volkswagen dasher'],
                    [22, 'datsun 810'],
                    [21.5, 'bmw 320i'],
                    [21.5, 'mazda rx-4'],
                    [43.1, 'volkswagen rabbit custom diesel'],
                    [36.1, 'ford fiesta'],
                    [32.8, 'mazda glc deluxe'],
                    [39.4, 'datsun b210 gx'],
                    [36.1, 'honda civic cvcc'],
                    [19.9, 'oldsmobile cutlass salon brougham'],
                    [19.4, 'dodge diplomat'],
                    [20.2, 'mercury monarch ghia'],
                    [19.2, 'pontiac phoenix lj'],
                    [20.5, 'chevrolet malibu'],
                    [20.2, 'ford fairmont (auto)'],
                    [25.1, 'ford fairmont (man)'],
                    [20.5, 'plymouth volare'],
                    [19.4, 'amc concord'],
                    [20.6, 'buick century special'],
                    [20.8, 'mercury zephyr'],
                    [18.6, 'dodge aspen'],
                    [18.1, 'amc concord d/l'],
                    [19.2, 'chevrolet monte carlo landau'],
                    [17.7, 'buick regal sport coupe (turbo)'],
                    [18.1, 'ford futura'],
                    [17.5, 'dodge magnum xe'],
                    [30, 'chevrolet chevette'],
                    [27.5, 'toyota corona'],
                    [27.2, 'datsun 510'],
                    [30.9, 'dodge omni'],
                    [21.1, 'toyota celica gt liftback'],
                    [23.2, 'plymouth sapporo'],
                    [23.8, 'oldsmobile starfire sx'],
                    [23.9, 'datsun 200-sx'],
                    [20.3, 'audi 5000'],
                    [17, 'volvo 264gl'],
                    [21.6, 'saab 99gle'],
                    [16.2, 'peugeot 604sl'],
                    [31.5, 'volkswagen scirocco'],
                    [29.5, 'honda accord lx'],
                    [21.5, 'pontiac lemans v6'],
                    [19.8, 'mercury zephyr 6'],
                    [22.3, 'ford fairmont 4'],
                    [20.2, 'amc concord dl 6'],
                    [20.6, 'dodge aspen 6'],
                    [17, 'chevrolet caprice classic'],
                    [17.6, 'ford ltd landau'],
                    [16.5, 'mercury grand marquis'],
                    [18.2, 'dodge st. regis'],
                    [16.9, 'buick estate wagon (sw)'],
                    [15.5, 'ford country squire (sw)'],
                    [19.2, 'chevrolet malibu classic (sw)'],
                    [18.5, 'chrysler lebaron town @ country (sw)'],
                    [31.9, 'vw rabbit custom'],
                    [34.1, 'maxda glc deluxe'],
                    [35.7, 'dodge colt hatchback custom'],
                    [27.4, 'amc spirit dl'],
                    [25.4, 'mercedes benz 300d'],
                    [23, 'cadillac eldorado'],
                    [27.2, 'peugeot 504'],
                    [23.9, 'oldsmobile cutlass salon brougham'],
                    [34.2, 'plymouth horizon'],
                    [34.5, 'plymouth horizon tc3'],
                    [31.8, 'datsun 210'],
                    [37.3, 'fiat strada custom'],
                    [28.4, 'buick skylark limited'],
                    [28.8, 'chevrolet citation'],
                    [26.8, 'oldsmobile omega brougham'],
                    [33.5, 'pontiac phoenix'],
                    [41.5, 'vw rabbit'],
                    [38.1, 'toyota corolla tercel'],
                    [32.1, 'chevrolet chevette'],
                    [37.2, 'datsun 310'],
                    [28, 'chevrolet citation'],
                    [26.4, 'ford fairmont'],
                    [24.3, 'amc concord'],
                    [19.1, 'dodge aspen'],
                    [34.3, 'audi 4000'],
                    [29.8, 'toyota corona liftback'],
                    [31.3, 'mazda 626'],
                    [37, 'datsun 510 hatchback'],
                    [32.2, 'toyota corolla'],
                    [46.6, 'mazda glc'],
                    [27.9, 'dodge colt'],
                    [40.8, 'datsun 210'],
                    [44.3, 'vw rabbit c (diesel)'],
                    [43.4, 'vw dasher (diesel)'],
                    [36.4, 'audi 5000s (diesel)'],
                    [30, 'mercedes-benz 240d'],
                    [44.6, 'honda civic 1500 gl'],
                    [33.8, 'subaru dl'],
                    [29.8, 'vokswagen rabbit'],
                    [32.7, 'datsun 280-zx'],
                    [23.7, 'mazda rx-7 gs'],
                    [35, 'triumph tr7 coupe'],
                    [32.4, 'honda accord'],
                    [27.2, 'plymouth reliant'],
                    [26.6, 'buick skylark'],
                    [25.8, 'dodge aries wagon (sw)'],
                    [23.5, 'chevrolet citation'],
                    [30, 'plymouth reliant'],
                    [39.1, 'toyota starlet'],
                    [39, 'plymouth champ'],
                    [35.1, 'honda civic 1300'],
                    [32.3, 'subaru'],
                    [37, 'datsun 210 mpg'],
                    [37.7, 'toyota tercel'],
                    [34.1, 'mazda glc 4'],
                    [34.7, 'plymouth horizon 4'],
                    [34.4, 'ford escort 4w'],
                    [29.9, 'ford escort 2h'],
                    [33, 'volkswagen jetta'],
                    [33.7, 'honda prelude'],
                    [32.4, 'toyota corolla'],
                    [32.9, 'datsun 200sx'],
                    [31.6, 'mazda 626'],
                    [28.1, 'peugeot 505s turbo diesel'],
                    [30.7, 'volvo diesel'],
                    [25.4, 'toyota cressida'],
                    [24.2, 'datsun 810 maxima'],
                    [22.4, 'buick century'],
                    [26.6, 'oldsmobile cutlass ls'],
                    [20.2, 'ford granada gl'],
                    [17.6, 'chrysler lebaron salon'],
                    [28, 'chevrolet cavalier'],
                    [27, 'chevrolet cavalier wagon'],
                    [34, 'chevrolet cavalier 2-door'],
                    [31, 'pontiac j2000 se hatchback'],
                    [29, 'dodge aries se'],
                    [27, 'pontiac phoenix'],
                    [24, 'ford fairmont futura'],
                    [36, 'volkswagen rabbit l'],
                    [37, 'mazda glc custom l'],
                    [31, 'mazda glc custom'],
                    [38, 'plymouth horizon miser'],
                    [36, 'mercury lynx l'],
                    [36, 'nissan stanza xe'],
                    [36, 'honda accord'],
                    [34, 'toyota corolla'],
                    [38, 'honda civic'],
                    [32, 'honda civic (auto)'],
                    [38, 'datsun 310 gx'],
                    [25, 'buick century limited'],
                    [38, 'oldsmobile cutlass ciera (diesel)'],
                    [26, 'chrysler lebaron medallion'],
                    [22, 'ford granada l'],
                    [32, 'toyota celica gt'],
                    [36, 'dodge charger 2.2'],
                    [27, 'chevrolet camaro'],
                    [27, 'ford mustang gl'],
                    [44, 'vw pickup'],
                    [32, 'dodge rampage'],
                    [28, 'ford ranger'],
                    [31, 'chevy s-10']]  # Hardcoded Data

try:
    auto_mpg = list()
    with open('auto-mpg_original.csv') as file:
        for line in list(file)[1:]:
            line = line.replace('\n', '')
            temp = [float(line.split(',')[0]), line.split(',')[-1]]
            auto_mpg.append(temp)
    car_mpg_car_name = auto_mpg  # Data from CSV
except:
    print("CSV not found, hard coded data preferred")


def pretty_print(dic):
    for i in dic:
        print('----------------------------------------------------', i, end='', sep="\n")
        for j in dic[i]:
            print("\t--->\t" + j)


# Part 1
dic = dict()
for i in car_mpg_car_name:
    dic[i[0]] = dic.get(i[0]) or set()
    dic[i[0]].add(i[1])
pretty_print(dic)

# Part 2
dic = dict()
for i in car_mpg_car_name:
    ls = i[1].split(maxsplit=1)
    if len(ls) < 2:
        ls.append(' ')
    dic[ls[0]] = dic.get(ls[0]) or set()
    dic[ls[0]].add(ls[1])
pretty_print(dic)
